export type HelpCenterFaq = {
  id: string;
  question: string;
  answer: string;
};

export const HELP_CENTER_FAQS: HelpCenterFaq[] = [
  {
    id: "what-is-worldloop",
    question: "What is WorldLoop?",
    answer:
      "WorldLoop is a travel discovery app that helps you explore countries through swipeable feeds, interactive maps, AI-generated facts, and landmark highlights — like a TikTok-style guide to the world.",
  },
  {
    id: "explore-countries",
    question: "How do I explore countries?",
    answer:
      "Open the Explore tab and swipe vertically to move between countries. Each country card includes photos, stats, and AI facts. Swipe horizontally inside a card to browse its media carousel.",
  },
  {
    id: "saved-vs-visited",
    question: "What's the difference between Saved and Visited?",
    answer:
      "Saved places are countries or landmarks you bookmark for later. Visited countries are ones you mark as places you've been. Both appear on your profile and help personalize your travel map.",
  },
  {
    id: "travel-map",
    question: "How does the travel map work?",
    answer:
      "The Map tab shows an interactive world map. Tap a country to preview it, see landmarks, and jump into country details. Your saved and visited places can appear as pins depending on your legend settings.",
  },
  {
    id: "landmarks",
    question: "What are landmarks?",
    answer:
      "Landmarks are notable places inside a country — monuments, parks, natural wonders, and cultural sites. Open a country profile to browse its top landmarks and tap one for photos, facts, and map location.",
  },
  {
    id: "ai-facts",
    question: "Where do the AI facts come from?",
    answer:
      "Fun facts and summaries are generated by AI using country data from trusted public sources. They're meant to be engaging starting points — always double-check important travel or safety information elsewhere.",
  },
  {
    id: "account",
    question: "Do I need an account?",
    answer:
      "Yes. Sign in with Clerk to sync your profile, saved places, and discovery progress across sessions on the same device.",
  },
  {
    id: "offline",
    question: "Can I use WorldLoop offline?",
    answer:
      "Some cached content may load without a connection, but full discovery features — maps, AI content, and fresh images — require internet. Offline map downloads are planned for a future update.",
  },
  {
    id: "report-issue",
    question: "How do I report a bug or ask a question?",
    answer:
      "Scroll to Contact support on this screen and copy our support email. Send us a message with your question, device model, and steps to reproduce any issue.",
  },
];
